spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://127.0.0.1:3306/security1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  # JPA
  jpa:
    # Specify the DBMS
    database: mysql
    #just fir test : log each sql query
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  servlet:
    session:
      timeout: 60